service: quiztopia-api-exam
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  profile: kentjs24

  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    DYNAMODB_TABLE: QuiztopiaUsers
    QUIZ_TABLE: QuiztopiaQuizzes
    RESULT_TABLE: QuiztopiaResults

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:CreateFunction
        - lambda:UpdateFunctionCode
        - lambda:UpdateFunctionConfiguration
        - lambda:DeleteFunction
      Resource: "arn:aws:lambda:eu-north-1:187296254059:function:quiztopia-*"

    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

    - Effect: Allow
      Action:
        - apigateway:GET
        - apigateway:POST
        - apigateway:PUT
        - apigateway:DELETE
        - apigateway:PATCH
      Resource: "*"

    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-north-1:187296254059:table/Quiztopia*"

plugins:
  - serverless-dotenv-plugin
  
functions:
  submitResult:
    handler: src/functions/scores/submit.main
    events:
      - http:
          path: scores/submit
          method: post
          cors: true
      - http:
          path: result
          method: post
          cors: true

  login:
    handler: src/functions/auth/login.main
    events:
      - http:
          path: auth/login
          method: post

  register:
    handler: src/functions/auth/register.main
    events:
      - http:
          path: auth/register
          method: post

  leaderboard:
    handler: src/functions/scores/leaderboard.main
    events:
      - http:
          path: leaderboard
          method: get

  createQuiz:
    handler: src/functions/quizzes/create.main
    events:
      - http:
          path: quizzes/create
          method: post
          cors: true

  getAllQuizzes:
    handler: src/functions/quizzes/getAll.main
    events:
      - http:
          path: quizzes
          method: get
          cors: true

  getOneQuiz:
    handler: src/functions/quizzes/getOne.main
    events:
      - http:
          path: quizzes/{quizId}
          method: get
          cors: true

  deleteQuiz:
    handler: src/functions/quizzes/delete.main
    events:
      - http:
          path: quizzes/{quizId}
          method: delete
          cors: true

  addQuestion:
    handler: src/functions/quizzes/addQuestion.main
    events:
      - http:
          path: quizzes/{quizId}/questions
          method: post
          cors: true

resources:
  Resources:
    QuiztopiaUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuiztopiaUsers
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    QuiztopiaQuizzesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuiztopiaQuizzes
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: type-index
            KeySchema:
              - AttributeName: type
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    QuiztopiaResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: QuiztopiaResults
        AttributeDefinitions:
          - AttributeName: resultId
            AttributeType: S
          - AttributeName: quizId
            AttributeType: S
        KeySchema:
          - AttributeName: resultId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: quizId-index
            KeySchema:
              - AttributeName: quizId
                KeyType: HASH
            Projection:
              ProjectionType: ALL